version: "3"

services:
  web:
    build: .
    image: codaya007/web:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    deploy:
      replicas: 1
    # environment:

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: FLASK_TEST
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      replicas: 1

volumes:
  db_data:
